# Generated by Django 4.2.6 on 2023-11-03 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routes',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AddField(
            model_name='routes',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Прибытие'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routes',
            name='big_text',
            field=models.TextField(verbose_name='куча текста'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='description',
            field=models.CharField(max_length=200, verbose_name='описание'),
        ),
    ]
