# Generated by Django 4.2.6 on 2023-11-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_carriage_carriage_type_route_station_seat_routepoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carriage',
            options={'verbose_name': 'Вагон', 'verbose_name_plural': 'Вагоны'},
        ),
        migrations.AlterModelOptions(
            name='carriage_type',
            options={'verbose_name': 'Тип вагона', 'verbose_name_plural': 'Типы вагонов'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
