# Generated by Django 4.2.6 on 2023-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_carriage_options_alter_carriage_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='train_story',
            field=models.CharField(default=1234, max_length=100, verbose_name='Заметка'),
            preserve_default=False,
        ),
    ]
