# Generated by Django 4.2.6 on 2023-11-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_remove_train_train_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название населённого пункта')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
            },
        ),
        migrations.RemoveField(
            model_name='station',
            name='id_city',
        ),
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.city'),
            preserve_default=False,
        ),
    ]
