# Generated by Django 4.2.6 on 2023-12-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_city_options_remove_routepoint_id_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='name',
            field=models.CharField(default='e3', max_length=50, verbose_name='ТЕСТ'),
            preserve_default=False,
        ),
    ]
