# Generated by Django 4.2.6 on 2023-12-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_city1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='id_train',
        ),
    ]
