# Generated by Django 4.2.6 on 2023-12-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_remove_route_id_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='id_train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.train'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='arrive_time',
            field=models.DateTimeField(null=True, verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='departure_time',
            field=models.DateTimeField(null=True, verbose_name='Время отправления'),
        ),
    ]
