# Generated by Django 4.2.6 on 2023-12-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_preticket_delete_city1_alter_routepoint_arrive_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preticket',
            name='id_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.route'),
            preserve_default=False,
        ),
    ]
