# Generated by Django 4.2.6 on 2023-12-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_preticket_id_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='preticket',
            name='tr_arr_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город прибытия рейса'),
        ),
        migrations.AddField(
            model_name='preticket',
            name='tr_dep_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город отправления рейса'),
        ),
        migrations.AlterField(
            model_name='preticket',
            name='arr_st_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название станции прибытия'),
        ),
    ]
