# Generated by Django 4.2.6 on 2024-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_preticket_tr_arr_city_preticket_tr_dep_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='base_price',
            field=models.IntegerField(default=100, verbose_name='Базовая цена билета'),
            preserve_default=False,
        ),
    ]
