# Generated by Django 4.2.6 on 2024-01-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_route_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='preticket',
            name='hops_count',
            field=models.IntegerField(default=1, verbose_name='Число хопов между этими станциями'),
            preserve_default=False,
        ),
    ]
