# Generated by Django 4.2.6 on 2024-01-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_preticket_hops_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price_coef',
            field=models.FloatField(default=1, verbose_name='Коэффициент цены'),
            preserve_default=False,
        ),
    ]
