# Generated by Django 4.2.6 on 2024-01-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_passanger_doc_info_passanger_doc_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passanger',
            name='doc_info',
        ),
        migrations.RemoveField(
            model_name='passanger',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='passanger',
            name='user_id',
        ),
    ]
