# Generated by Django 4.2.6 on 2024-01-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_passanger_doc_info_passanger_doc_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.passanger')),
                ('id_preticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.preticket')),
            ],
        ),
    ]
