# Generated by Django 4.2.6 on 2024-02-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_place',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.PROTECT, to='timetable.seat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(default=666, verbose_name='Цена за билет'),
            preserve_default=False,
        ),
    ]
