# Generated by Django 4.2.6 on 2024-02-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_remove_seat_name_ticket_id_place_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='preticket',
            name='day_dif',
            field=models.IntegerField(default=100, verbose_name='Разница в днях от эталона'),
            preserve_default=False,
        ),
    ]
