# Generated by Django 4.2.6 on 2024-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_preticket_day_dif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routes',
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='boarding',
            field=models.BooleanField(default=True, verbose_name='Посадка в поезд'),
        ),
    ]
